### ISSUE TITLE
Add to meta lists

### ISSUE THREAD

**Issue by thisismydesign** [componently-com/awesome-building-blocks-for-web-apps#1]
https://github.com/sindresorhus/awesome
https://github.com/bayandin/awesome-awesomeness
https://github.com/jnv/lists

Dead:
- https://github.com/pshah123/awesome-lists

**Comment by thisismydesign** [comment]
https://github.com/sindresorhus/awesome/pull/1789

**Comment by thisismydesign** [comment]
https://github.com/bayandin/awesome-awesomeness/pull/411

**Comment by thisismydesign** [comment]
https://github.com/jnv/lists/pull/154 - merged

**Comment by dbartholomae** [comment]
sindresorhus/awesome#1796
